### ISSUE TITLE
Set global directory for texfrags

### ISSUE THREAD

**Issue by mroman42** [TobiasZawada/texfrag#24]
The sub-directory for preview data can be customized in `texfrag-subdir`. Is it possible to use a single global directory for all texfrags? Say, `~/.texfrag`?

Perhaps related to #14.

**Comment by TobiasZawada** [comment]
Using a single global directory is possible with some (very) minor constraints.
Those constraints should not be visible if you do not access the LaTeX file corresponding to the file with active `texfrag-mode`.
Thus you should not notify any negative effects of the absolute path as "normal" texfrag user.
Open a new issue if anything goes wrong.

I've just changed the code a bit to allow absolute directories when the default directory of the file with active `texfrag-mode` is write-protected.

Pityingly, cleaning up the mess of temporary files is not yet implemented.

**Comment by mroman42** [comment]
I see, this is 8b4159b59b510c9afd42ec6d8c19078b75b4f778. I think that closes the issue. Thank you for texfrag, it is amazing on org-mode files.

**Comment by TobiasZawada** [comment]
Hm, there slipped one of those spurious edits through. `testing` -> `testig` ?!
I really checked the diff before the commit. Don't know how this could slip through.
I will correct this spello with the next commit. Otherwise the commit is clean.
I did the planned test. That test does intentionally not include a special case for the absolute path in `texfrag-subdir`.
No test can cover all special cases and it is important to avoid bloating of the test.
You know how to report when you stumble across a bug.
Thanks for the report by the way.
